#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap/app.php';

/**
 * Create a new instance of the Symfony Console Application.
 */
$application = new \Symfony\Component\Console\Application();

require_once __DIR__."/config/cli-commands.php";

$application->run();


